
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ruby_react_development


test:
  <<: *default
  database: ruby_react_test


production:
  <<: *default
  database: ruby_react_production
  username: ruby_react
  password: <%= ENV['RUBY_REACT_DATABASE_PASSWORD'] %>
